FROM python:1-3.13-slim

WORKDIR /app

COPY ./backend/requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./backend/src /app/src

CMD ["fastapi", "run", "src/main.py", "--port", "8080"]

HEALTHCHECK --interval=30s --timeout=10s --start-period=10s --retries=1 \
    CMD curl -s --fail http://localhost:8080/health-check | grep '"healthy":true' > /dev/null || exit 1